name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-gif-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-gif-app:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/flask-deployment flask-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-gif-app:${{ github.sha }}
